// https://pictogrammers.com/library/mdi/
import {
  mdiMonitor,
  mdiImageMultiple,
  mdiCog,
  mdiAccountMultiple,
  mdiPaletteSwatch,
  mdiDatabase,
  mdiCardAccountDetails,
  mdiMessageText,
  mdiEmail,
  mdiTooltipAccount,
  mdiTruckDelivery,
  mdiGift,
  mdiStorefront,
  mdiCloudDownload,
  mdiChartAreasplineVariant,
  mdiCheckboxMarkedCircleAutoOutline,
  mdiFileExport,
  mdiDoctor,
  mdiClockTimeTwo,
  mdiStarCircle,
  mdiTooltipQuestion,
  mdiStoreSettingsOutline,
  mdiTrademark
} from "@mdi/js";

export default [{
  to: "/dashboard",
  icon: mdiMonitor,
  label: "Dashboard",
},
  {
    to: null,
    label: "Patient",
  },
  {
    to: "/patient",
    permission: 'Patient.menu',
    icon: mdiCardAccountDetails,
    label: "Patient",
  },
  {
    to: "/task",
    permission: 'Task.menu',
    icon: mdiCheckboxMarkedCircleAutoOutline,
    label: "Task",
  },
  {
    to: null,
    permission: 'Inventory.menu',
    label: "Inventory",
  },
  {
    to: "/delivery",
    permission: 'Delivery.menu',
    label: "Delivery",
    icon: mdiTruckDelivery,
    disable: true,
  },
  {
    to: "/inventory",
    permission: 'Inventory.menu',
    label: "Inventory",
    icon: mdiStorefront,
    disable: false,
  },
  {
    to: "/product",
    permission: 'Product.menu',
    label: "Product",
    icon: mdiGift,
    disable: false,
  },
  {
    to: "/supplier",
    permission: 'Supplier.menu',
    label: "Supplier",
    icon: mdiStoreSettingsOutline,
    disable: false,
  },
  {
    to: "/trademark",
    permission: 'Trademark.menu',
    label: "Trademark",
    icon: mdiTrademark,
    disable: false,
  },
  {
    to: null,
    label: "Marketing",
  },
  {
    to: "/email",
    permission: 'Email.menu',
    label: "Email",
    icon: mdiMessageText,
  },
  {
    to: "/sms",
    permission: 'Sms.menu',
    label: "SMS",
    icon: mdiEmail,
    disable: true,
  },
  {
    to: null,
    label: "Other",
  },
  {
    to: "/user",
    permission: 'User.menu',
    label: "Users",
    icon: mdiAccountMultiple,
  },
  {
    label: "Customers",
    icon: mdiTooltipAccount,
    permission: 'Customers.menu',
    menu: [{
      to: "/customers",
      label: "Customers list"
    },
      {
        to: "/customer-group",
        label: "Customer group",
      },
    ],
    disable: true,
  },
  {
    to: "/doctor",
    permission: "Doctor.menu",
    label: "Doctors",
    icon: mdiDoctor,
  },
  {
    to: "/points",
    permission: 'Points.menu',
    label: "Point",
    icon: mdiStarCircle,
    disable: true,
  },
  {
    permission: 'File.menu',
    label: "File Manager",
    icon: mdiImageMultiple,
    to: "/files",
  },
  {
    to: null,
    label: "System",
  },
  {
    to: "/report",
    label: "Report",
    permission: 'Report.menu',
    icon: mdiChartAreasplineVariant,
    disable: true,
  },
  {
    to: "/logs",
    permission: 'Logs.menu',
    label: "Logs",
    icon: mdiClockTimeTwo,
  },
  {
    to: "/forms",
    permission: 'Forms.menu',
    label: "Forms",
    icon: mdiFileExport,
    disable: true,
  },
  {
    label: "Backup",
    permission: 'Backup.menu',
    icon: mdiCloudDownload,
    to: "/backup",
    disable: true,
  },
  {
    label: "FAQs",
    icon: mdiTooltipQuestion,
    to: "/faqs",
    disable: true,
  },
  {
    to: null,
    permission: 'Setting',
    label: "Platform",
  },
  {
    permission: 'MasterData.menu',
    label: "Master Data",
    icon: mdiDatabase,
    to: "/master-data",
  },
  {
    permission: 'Config.menu',
    label: "System Config",
    icon: mdiCog,
    to: "/configs/general",
  },
  {
    permission: 'Template.menu',
    label: "Template",
    icon: mdiPaletteSwatch,
    to: "/email/templates",
    disable: true,
    // menu: [
    //   {
    //     to: "/email/templates",
    //     label: "Email",
    //   } ,
    //   {
    //     to: "/invoice/templates",
    //     label: "Invoice",
    //   }
    // ],
  }
];
