/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1_3306
 Source Server Type    : MySQL
 Source Server Version : 80032
 Source Host           : 127.0.0.1:3306
 Source Schema         : evisa

 Target Server Type    : MySQL
 Target Server Version : 80032
 File Encoding         : 65001

 Date: 04/08/2023 10:05:12
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for districts
-- ----------------------------
DROP TABLE IF EXISTS `districts`;
CREATE TABLE `districts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `province_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'A',
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `districts_name_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=708 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of districts
-- ----------------------------
BEGIN;
INSERT INTO `districts` VALUES (2, 'Quận Ba Đình', '001', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (3, 'Quận Hoàn Kiếm', '002', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (4, 'Quận Tây Hồ', '003', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (5, 'Quận Long Biên', '004', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (6, 'Quận Cầu Giấy', '005', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (7, 'Quận Đống Đa', '006', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (8, 'Quận Hai Bà Trưng', '007', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (9, 'Quận Hoàng Mai', '008', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (10, 'Quận Thanh Xuân', '009', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (11, 'Huyện Sóc Sơn', '016', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (12, 'Huyện Đông Anh', '017', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (13, 'Huyện Gia Lâm', '018', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (14, 'Quận Nam Từ Liêm', '019', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (15, 'Huyện Thanh Trì', '020', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (16, 'Quận Bắc Từ Liêm', '021', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (17, 'Huyện Mê Linh', '250', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (18, 'Quận Hà Đông', '268', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (19, 'Thị xã Sơn Tây', '269', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (20, 'Huyện Ba Vì', '271', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (21, 'Huyện Phúc Thọ', '272', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (22, 'Huyện Đan Phượng', '273', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (23, 'Huyện Hoài Đức', '274', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (24, 'Huyện Quốc Oai', '275', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (25, 'Huyện Thạch Thất', '276', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (26, 'Huyện Chương Mỹ', '277', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (27, 'Huyện Thanh Oai', '278', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (28, 'Huyện Thường Tín', '279', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (29, 'Huyện Phú Xuyên', '280', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (30, 'Huyện Ứng Hòa', '281', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (31, 'Huyện Mỹ Đức', '282', 'VN', '01', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (32, 'Thành phố Hà Giang', '024', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (33, 'Huyện Đồng Văn', '026', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (34, 'Huyện Mèo Vạc', '027', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (35, 'Huyện Yên Minh', '028', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (36, 'Huyện Quản Bạ', '029', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (37, 'Huyện Vị Xuyên', '030', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (38, 'Huyện Bắc Mê', '031', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (39, 'Huyện Hoàng Su Phì', '032', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (40, 'Huyện Xín Mần', '033', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (41, 'Huyện Bắc Quang', '034', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (42, 'Huyện Quang Bình', '035', 'VN', '02', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (43, 'Thành phố Cao Bằng', '040', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (44, 'Huyện Bảo Lâm', '042', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (45, 'Huyện Bảo Lạc', '043', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (46, 'Huyện Hà Quảng', '045', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (47, 'Huyện Trùng Khánh', '047', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (48, 'Huyện Hạ Lang', '048', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (49, 'Huyện Quảng Hòa', '049', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (50, 'Huyện Hoà An', '051', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (51, 'Huyện Nguyên Bình', '052', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (52, 'Huyện Thạch An', '053', 'VN', '04', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (53, 'Thành Phố Bắc Kạn', '058', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (54, 'Huyện Pác Nặm', '060', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (55, 'Huyện Ba Bể', '061', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (56, 'Huyện Ngân Sơn', '062', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (57, 'Huyện Bạch Thông', '063', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (58, 'Huyện Chợ Đồn', '064', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (59, 'Huyện Chợ Mới', '065', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (60, 'Huyện Na Rì', '066', 'VN', '06', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (61, 'Thành phố Tuyên Quang', '070', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (62, 'Huyện Lâm Bình', '071', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (63, 'Huyện Na Hang', '072', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (64, 'Huyện Chiêm Hóa', '073', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (65, 'Huyện Hàm Yên', '074', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (66, 'Huyện Yên Sơn', '075', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (67, 'Huyện Sơn Dương', '076', 'VN', '08', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (68, 'Thành phố Lào Cai', '080', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (69, 'Huyện Bát Xát', '082', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (70, 'Huyện Mường Khương', '083', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (71, 'Huyện Si Ma Cai', '084', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (72, 'Huyện Bắc Hà', '085', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (73, 'Huyện Bảo Thắng', '086', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (74, 'Huyện Bảo Yên', '087', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (75, 'Thị xã Sa Pa', '088', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (76, 'Huyện Văn Bàn', '089', 'VN', '10', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (77, 'Thành phố Điện Biên Phủ', '094', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (78, 'Thị Xã Mường Lay', '095', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (79, 'Huyện Mường Nhé', '096', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (80, 'Huyện Mường Chà', '097', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (81, 'Huyện Tủa Chùa', '098', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (82, 'Huyện Tuần Giáo', '099', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (83, 'Huyện Điện Biên', '100', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (84, 'Huyện Điện Biên Đông', '101', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (85, 'Huyện Mường Ảng', '102', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (86, 'Huyện Nậm Pồ', '103', 'VN', '11', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (87, 'Thành phố Lai Châu', '105', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (88, 'Huyện Tam Đường', '106', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (89, 'Huyện Mường Tè', '107', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (90, 'Huyện Sìn Hồ', '108', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (91, 'Huyện Phong Thổ', '109', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (92, 'Huyện Than Uyên', '110', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (93, 'Huyện Tân Uyên', '111', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (94, 'Huyện Nậm Nhùn', '112', 'VN', '12', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (95, 'Thành phố Sơn La', '116', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (96, 'Huyện Quỳnh Nhai', '118', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (97, 'Huyện Thuận Châu', '119', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (98, 'Huyện Mường La', '120', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (99, 'Huyện Bắc Yên', '121', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (100, 'Huyện Phù Yên', '122', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (101, 'Huyện Mộc Châu', '123', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (102, 'Huyện Yên Châu', '124', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (103, 'Huyện Mai Sơn', '125', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (104, 'Huyện Sông Mã', '126', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (105, 'Huyện Sốp Cộp', '127', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (106, 'Huyện Vân Hồ', '128', 'VN', '14', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (107, 'Thành phố Yên Bái', '132', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (108, 'Thị xã Nghĩa Lộ', '133', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (109, 'Huyện Lục Yên', '135', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (110, 'Huyện Văn Yên', '136', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (111, 'Huyện Mù Căng Chải', '137', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (112, 'Huyện Trấn Yên', '138', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (113, 'Huyện Trạm Tấu', '139', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (114, 'Huyện Văn Chấn', '140', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (115, 'Huyện Yên Bình', '141', 'VN', '15', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (116, 'Thành phố Hòa Bình', '148', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (117, 'Huyện Đà Bắc', '150', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (118, 'Huyện Lương Sơn', '152', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (119, 'Huyện Kim Bôi', '153', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (120, 'Huyện Cao Phong', '154', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (121, 'Huyện Tân Lạc', '155', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (122, 'Huyện Mai Châu', '156', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (123, 'Huyện Lạc Sơn', '157', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (124, 'Huyện Yên Thủy', '158', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (125, 'Huyện Lạc Thủy', '159', 'VN', '17', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (126, 'Thành phố Thái Nguyên', '164', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (127, 'Thành phố Sông Công', '165', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (128, 'Huyện Định Hóa', '167', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (129, 'Huyện Phú Lương', '168', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (130, 'Huyện Đồng Hỷ', '169', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (131, 'Huyện Võ Nhai', '170', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (132, 'Huyện Đại Từ', '171', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (133, 'Thành phố Phổ Yên', '172', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (134, 'Huyện Phú Bình', '173', 'VN', '19', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (135, 'Thành phố Lạng Sơn', '178', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (136, 'Huyện Tràng Định', '180', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (137, 'Huyện Bình Gia', '181', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (138, 'Huyện Văn Lãng', '182', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (139, 'Huyện Cao Lộc', '183', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (140, 'Huyện Văn Quan', '184', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (141, 'Huyện Bắc Sơn', '185', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (142, 'Huyện Hữu Lũng', '186', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (143, 'Huyện Chi Lăng', '187', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (144, 'Huyện Lộc Bình', '188', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (145, 'Huyện Đình Lập', '189', 'VN', '20', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (146, 'Thành phố Hạ Long', '193', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (147, 'Thành phố Móng Cái', '194', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (148, 'Thành phố Cẩm Phả', '195', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (149, 'Thành phố Uông Bí', '196', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (150, 'Huyện Bình Liêu', '198', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (151, 'Huyện Tiên Yên', '199', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (152, 'Huyện Đầm Hà', '200', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (153, 'Huyện Hải Hà', '201', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (154, 'Huyện Ba Chẽ', '202', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (155, 'Huyện Vân Đồn', '203', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (156, 'Thị xã Đông Triều', '205', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (157, 'Thị xã Quảng Yên', '206', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (158, 'Huyện Cô Tô', '207', 'VN', '22', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (159, 'Thành phố Bắc Giang', '213', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (160, 'Huyện Yên Thế', '215', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (161, 'Huyện Tân Yên', '216', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (162, 'Huyện Lạng Giang', '217', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (163, 'Huyện Lục Nam', '218', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (164, 'Huyện Lục Ngạn', '219', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (165, 'Huyện Sơn Động', '220', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (166, 'Huyện Yên Dũng', '221', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (167, 'Huyện Việt Yên', '222', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (168, 'Huyện Hiệp Hòa', '223', 'VN', '24', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (169, 'Thành phố Việt Trì', '227', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (170, 'Thị xã Phú Thọ', '228', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (171, 'Huyện Đoan Hùng', '230', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (172, 'Huyện Hạ Hoà', '231', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (173, 'Huyện Thanh Ba', '232', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (174, 'Huyện Phù Ninh', '233', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (175, 'Huyện Yên Lập', '234', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (176, 'Huyện Cẩm Khê', '235', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (177, 'Huyện Tam Nông', '236', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (178, 'Huyện Lâm Thao', '237', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (179, 'Huyện Thanh Sơn', '238', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (180, 'Huyện Thanh Thuỷ', '239', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (181, 'Huyện Tân Sơn', '240', 'VN', '25', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (182, 'Thành phố Vĩnh Yên', '243', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (183, 'Thành phố Phúc Yên', '244', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (184, 'Huyện Lập Thạch', '246', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (185, 'Huyện Tam Dương', '247', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (186, 'Huyện Tam Đảo', '248', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (187, 'Huyện Bình Xuyên', '249', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (188, 'Huyện Yên Lạc', '251', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (189, 'Huyện Vĩnh Tường', '252', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (190, 'Huyện Sông Lô', '253', 'VN', '26', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (191, 'Thành phố Bắc Ninh', '256', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (192, 'Huyện Yên Phong', '258', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (193, 'Huyện Quế Võ', '259', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (194, 'Huyện Tiên Du', '260', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (195, 'Thành phố Từ Sơn', '261', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (196, 'Huyện Thuận Thành', '262', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (197, 'Huyện Gia Bình', '263', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (198, 'Huyện Lương Tài', '264', 'VN', '27', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (199, 'Thành phố Hải Dương', '288', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (200, 'Thành phố Chí Linh', '290', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (201, 'Huyện Nam Sách', '291', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (202, 'Thị xã Kinh Môn', '292', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (203, 'Huyện Kim Thành', '293', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (204, 'Huyện Thanh Hà', '294', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (205, 'Huyện Cẩm Giàng', '295', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (206, 'Huyện Bình Giang', '296', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (207, 'Huyện Gia Lộc', '297', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (208, 'Huyện Tứ Kỳ', '298', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (209, 'Huyện Ninh Giang', '299', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (210, 'Huyện Thanh Miện', '300', 'VN', '30', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (211, 'Quận Hồng Bàng', '303', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (212, 'Quận Ngô Quyền', '304', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (213, 'Quận Lê Chân', '305', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (214, 'Quận Hải An', '306', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (215, 'Quận Kiến An', '307', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (216, 'Quận Đồ Sơn', '308', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (217, 'Quận Dương Kinh', '309', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (218, 'Huyện Thuỷ Nguyên', '311', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (219, 'Huyện An Dương', '312', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (220, 'Huyện An Lão', '313', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (221, 'Huyện Kiến Thuỵ', '314', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (222, 'Huyện Tiên Lãng', '315', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (223, 'Huyện Vĩnh Bảo', '316', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (224, 'Huyện Cát Hải', '317', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (225, 'Huyện Bạch Long Vĩ', '318', 'VN', '31', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (226, 'Thành phố Hưng Yên', '323', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (227, 'Huyện Văn Lâm', '325', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (228, 'Huyện Văn Giang', '326', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (229, 'Huyện Yên Mỹ', '327', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (230, 'Thị xã Mỹ Hào', '328', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (231, 'Huyện Ân Thi', '329', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (232, 'Huyện Khoái Châu', '330', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (233, 'Huyện Kim Động', '331', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (234, 'Huyện Tiên Lữ', '332', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (235, 'Huyện Phù Cừ', '333', 'VN', '33', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (236, 'Thành phố Thái Bình', '336', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (237, 'Huyện Quỳnh Phụ', '338', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (238, 'Huyện Hưng Hà', '339', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (239, 'Huyện Đông Hưng', '340', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (240, 'Huyện Thái Thụy', '341', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (241, 'Huyện Tiền Hải', '342', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (242, 'Huyện Kiến Xương', '343', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (243, 'Huyện Vũ Thư', '344', 'VN', '34', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (244, 'Thành phố Phủ Lý', '347', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (245, 'Thị xã Duy Tiên', '349', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (246, 'Huyện Kim Bảng', '350', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (247, 'Huyện Thanh Liêm', '351', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (248, 'Huyện Bình Lục', '352', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (249, 'Huyện Lý Nhân', '353', 'VN', '35', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (250, 'Thành phố Nam Định', '356', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (251, 'Huyện Mỹ Lộc', '358', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (252, 'Huyện Vụ Bản', '359', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (253, 'Huyện Ý Yên', '360', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (254, 'Huyện Nghĩa Hưng', '361', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (255, 'Huyện Nam Trực', '362', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (256, 'Huyện Trực Ninh', '363', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (257, 'Huyện Xuân Trường', '364', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (258, 'Huyện Giao Thủy', '365', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (259, 'Huyện Hải Hậu', '366', 'VN', '36', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (260, 'Thành phố Ninh Bình', '369', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (261, 'Thành phố Tam Điệp', '370', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (262, 'Huyện Nho Quan', '372', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (263, 'Huyện Gia Viễn', '373', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (264, 'Huyện Hoa Lư', '374', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (265, 'Huyện Yên Khánh', '375', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (266, 'Huyện Kim Sơn', '376', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (267, 'Huyện Yên Mô', '377', 'VN', '37', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (268, 'Thành phố Thanh Hóa', '380', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (269, 'Thị xã Bỉm Sơn', '381', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (270, 'Thành phố Sầm Sơn', '382', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (271, 'Huyện Mường Lát', '384', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (272, 'Huyện Quan Hóa', '385', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (273, 'Huyện Bá Thước', '386', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (274, 'Huyện Quan Sơn', '387', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (275, 'Huyện Lang Chánh', '388', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (276, 'Huyện Ngọc Lặc', '389', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (277, 'Huyện Cẩm Thủy', '390', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (278, 'Huyện Thạch Thành', '391', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (279, 'Huyện Hà Trung', '392', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (280, 'Huyện Vĩnh Lộc', '393', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (281, 'Huyện Yên Định', '394', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (282, 'Huyện Thọ Xuân', '395', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (283, 'Huyện Thường Xuân', '396', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (284, 'Huyện Triệu Sơn', '397', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (285, 'Huyện Thiệu Hóa', '398', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (286, 'Huyện Hoằng Hóa', '399', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (287, 'Huyện Hậu Lộc', '400', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (288, 'Huyện Nga Sơn', '401', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (289, 'Huyện Như Xuân', '402', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (290, 'Huyện Như Thanh', '403', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (291, 'Huyện Nông Cống', '404', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (292, 'Huyện Đông Sơn', '405', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (293, 'Huyện Quảng Xương', '406', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (294, 'Thị xã Nghi Sơn', '407', 'VN', '38', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (295, 'Thành phố Vinh', '412', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (296, 'Thị xã Cửa Lò', '413', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (297, 'Thị xã Thái Hoà', '414', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (298, 'Huyện Quế Phong', '415', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (299, 'Huyện Quỳ Châu', '416', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (300, 'Huyện Kỳ Sơn', '417', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (301, 'Huyện Tương Dương', '418', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (302, 'Huyện Nghĩa Đàn', '419', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (303, 'Huyện Quỳ Hợp', '420', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (304, 'Huyện Quỳnh Lưu', '421', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (305, 'Huyện Con Cuông', '422', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (306, 'Huyện Tân Kỳ', '423', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (307, 'Huyện Anh Sơn', '424', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (308, 'Huyện Diễn Châu', '425', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (309, 'Huyện Yên Thành', '426', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (310, 'Huyện Đô Lương', '427', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (311, 'Huyện Thanh Chương', '428', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (312, 'Huyện Nghi Lộc', '429', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (313, 'Huyện Nam Đàn', '430', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (314, 'Huyện Hưng Nguyên', '431', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (315, 'Thị xã Hoàng Mai', '432', 'VN', '40', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (316, 'Thành phố Hà Tĩnh', '436', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (317, 'Thị xã Hồng Lĩnh', '437', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (318, 'Huyện Hương Sơn', '439', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (319, 'Huyện Đức Thọ', '440', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (320, 'Huyện Vũ Quang', '441', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (321, 'Huyện Nghi Xuân', '442', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (322, 'Huyện Can Lộc', '443', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (323, 'Huyện Hương Khê', '444', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (324, 'Huyện Thạch Hà', '445', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (325, 'Huyện Cẩm Xuyên', '446', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (326, 'Huyện Kỳ Anh', '447', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (327, 'Huyện Lộc Hà', '448', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (328, 'Thị xã Kỳ Anh', '449', 'VN', '42', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (329, 'Thành Phố Đồng Hới', '450', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (330, 'Huyện Minh Hóa', '452', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (331, 'Huyện Tuyên Hóa', '453', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (332, 'Huyện Quảng Trạch', '454', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (333, 'Huyện Bố Trạch', '455', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (334, 'Huyện Quảng Ninh', '456', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (335, 'Huyện Lệ Thủy', '457', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (336, 'Thị xã Ba Đồn', '458', 'VN', '44', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (337, 'Thành phố Đông Hà', '461', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (338, 'Thị xã Quảng Trị', '462', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (339, 'Huyện Vĩnh Linh', '464', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (340, 'Huyện Hướng Hóa', '465', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (341, 'Huyện Gio Linh', '466', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (342, 'Huyện Đa Krông', '467', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (343, 'Huyện Cam Lộ', '468', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (344, 'Huyện Triệu Phong', '469', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (345, 'Huyện Hải Lăng', '470', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (346, 'Huyện Cồn Cỏ', '471', 'VN', '45', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (347, 'Thành phố Huế', '474', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (348, 'Huyện Phong Điền', '476', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (349, 'Huyện Quảng Điền', '477', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (350, 'Huyện Phú Vang', '478', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (351, 'Thị xã Hương Thủy', '479', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (352, 'Thị xã Hương Trà', '480', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (353, 'Huyện A Lưới', '481', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (354, 'Huyện Phú Lộc', '482', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (355, 'Huyện Nam Đông', '483', 'VN', '46', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (356, 'Quận Liên Chiểu', '490', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (357, 'Quận Thanh Khê', '491', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (358, 'Quận Hải Châu', '492', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (359, 'Quận Sơn Trà', '493', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (360, 'Quận Ngũ Hành Sơn', '494', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (361, 'Quận Cẩm Lệ', '495', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (362, 'Huyện Hòa Vang', '497', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (363, 'Huyện Hoàng Sa', '498', 'VN', '48', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (364, 'Thành phố Tam Kỳ', '502', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (365, 'Thành phố Hội An', '503', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (366, 'Huyện Tây Giang', '504', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (367, 'Huyện Đông Giang', '505', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (368, 'Huyện Đại Lộc', '506', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (369, 'Thị xã Điện Bàn', '507', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (370, 'Huyện Duy Xuyên', '508', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (371, 'Huyện Quế Sơn', '509', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (372, 'Huyện Nam Giang', '510', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (373, 'Huyện Phước Sơn', '511', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (374, 'Huyện Hiệp Đức', '512', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (375, 'Huyện Thăng Bình', '513', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (376, 'Huyện Tiên Phước', '514', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (377, 'Huyện Bắc Trà My', '515', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (378, 'Huyện Nam Trà My', '516', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (379, 'Huyện Núi Thành', '517', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (380, 'Huyện Phú Ninh', '518', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (381, 'Huyện Nông Sơn', '519', 'VN', '49', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (382, 'Thành phố Quảng Ngãi', '522', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (383, 'Huyện Bình Sơn', '524', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (384, 'Huyện Trà Bồng', '525', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (385, 'Huyện Sơn Tịnh', '527', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (386, 'Huyện Tư Nghĩa', '528', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (387, 'Huyện Sơn Hà', '529', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (388, 'Huyện Sơn Tây', '530', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (389, 'Huyện Minh Long', '531', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (390, 'Huyện Nghĩa Hành', '532', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (391, 'Huyện Mộ Đức', '533', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (392, 'Thị xã Đức Phổ', '534', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (393, 'Huyện Ba Tơ', '535', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (394, 'Huyện Lý Sơn', '536', 'VN', '51', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (395, 'Thành phố Quy Nhơn', '540', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (396, 'Huyện An Lão', '542', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (397, 'Thị xã Hoài Nhơn', '543', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (398, 'Huyện Hoài Ân', '544', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (399, 'Huyện Phù Mỹ', '545', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (400, 'Huyện Vĩnh Thạnh', '546', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (401, 'Huyện Tây Sơn', '547', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (402, 'Huyện Phù Cát', '548', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (403, 'Thị xã An Nhơn', '549', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (404, 'Huyện Tuy Phước', '550', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (405, 'Huyện Vân Canh', '551', 'VN', '52', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (406, 'Thành phố Tuy Hoà', '555', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (407, 'Thị xã Sông Cầu', '557', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (408, 'Huyện Đồng Xuân', '558', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (409, 'Huyện Tuy An', '559', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (410, 'Huyện Sơn Hòa', '560', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (411, 'Huyện Sông Hinh', '561', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (412, 'Huyện Tây Hoà', '562', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (413, 'Huyện Phú Hoà', '563', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (414, 'Thị xã Đông Hòa', '564', 'VN', '54', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (415, 'Thành phố Nha Trang', '568', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (416, 'Thành phố Cam Ranh', '569', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (417, 'Huyện Cam Lâm', '570', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (418, 'Huyện Vạn Ninh', '571', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (419, 'Thị xã Ninh Hòa', '572', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (420, 'Huyện Khánh Vĩnh', '573', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (421, 'Huyện Diên Khánh', '574', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (422, 'Huyện Khánh Sơn', '575', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (423, 'Huyện Trường Sa', '576', 'VN', '56', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (424, 'Thành phố Phan Rang-Tháp Chàm', '582', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (425, 'Huyện Bác Ái', '584', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (426, 'Huyện Ninh Sơn', '585', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (427, 'Huyện Ninh Hải', '586', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (428, 'Huyện Ninh Phước', '587', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (429, 'Huyện Thuận Bắc', '588', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (430, 'Huyện Thuận Nam', '589', 'VN', '58', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (431, 'Thành phố Phan Thiết', '593', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (432, 'Thị xã La Gi', '594', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (433, 'Huyện Tuy Phong', '595', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (434, 'Huyện Bắc Bình', '596', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (435, 'Huyện Hàm Thuận Bắc', '597', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (436, 'Huyện Hàm Thuận Nam', '598', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (437, 'Huyện Tánh Linh', '599', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (438, 'Huyện Đức Linh', '600', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (439, 'Huyện Hàm Tân', '601', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (440, 'Huyện Phú Quí', '602', 'VN', '60', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (441, 'Thành phố Kon Tum', '608', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (442, 'Huyện Đắk Glei', '610', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (443, 'Huyện Ngọc Hồi', '611', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (444, 'Huyện Đắk Tô', '612', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (445, 'Huyện Kon Plông', '613', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (446, 'Huyện Kon Rẫy', '614', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (447, 'Huyện Đắk Hà', '615', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (448, 'Huyện Sa Thầy', '616', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (449, 'Huyện Tu Mơ Rông', '617', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (450, 'Huyện Ia H\' Drai', '618', 'VN', '62', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (451, 'Thành phố Pleiku', '622', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (452, 'Thị xã An Khê', '623', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (453, 'Thị xã Ayun Pa', '624', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (454, 'Huyện KBang', '625', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (455, 'Huyện Đăk Đoa', '626', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (456, 'Huyện Chư Păh', '627', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (457, 'Huyện Ia Grai', '628', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (458, 'Huyện Mang Yang', '629', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (459, 'Huyện Kông Chro', '630', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (460, 'Huyện Đức Cơ', '631', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (461, 'Huyện Chư Prông', '632', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (462, 'Huyện Chư Sê', '633', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (463, 'Huyện Đăk Pơ', '634', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (464, 'Huyện Ia Pa', '635', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (465, 'Huyện Krông Pa', '637', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (466, 'Huyện Phú Thiện', '638', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (467, 'Huyện Chư Pưh', '639', 'VN', '64', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (468, 'Thành phố Buôn Ma Thuột', '643', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (469, 'Thị Xã Buôn Hồ', '644', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (470, 'Huyện Ea H\'leo', '645', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (471, 'Huyện Ea Súp', '646', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (472, 'Huyện Buôn Đôn', '647', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (473, 'Huyện Cư M\'gar', '648', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (474, 'Huyện Krông Búk', '649', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (475, 'Huyện Krông Năng', '650', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (476, 'Huyện Ea Kar', '651', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (477, 'Huyện M\'Đrắk', '652', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (478, 'Huyện Krông Bông', '653', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (479, 'Huyện Krông Pắc', '654', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (480, 'Huyện Krông A Na', '655', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (481, 'Huyện Lắk', '656', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (482, 'Huyện Cư Kuin', '657', 'VN', '66', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (483, 'Thành phố Gia Nghĩa', '660', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (484, 'Huyện Đăk Glong', '661', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (485, 'Huyện Cư Jút', '662', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (486, 'Huyện Đắk Mil', '663', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (487, 'Huyện Krông Nô', '664', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (488, 'Huyện Đắk Song', '665', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (489, 'Huyện Đắk R\'Lấp', '666', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (490, 'Huyện Tuy Đức', '667', 'VN', '67', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (491, 'Thành phố Đà Lạt', '672', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (492, 'Thành phố Bảo Lộc', '673', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (493, 'Huyện Đam Rông', '674', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (494, 'Huyện Lạc Dương', '675', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (495, 'Huyện Lâm Hà', '676', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (496, 'Huyện Đơn Dương', '677', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (497, 'Huyện Đức Trọng', '678', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (498, 'Huyện Di Linh', '679', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (499, 'Huyện Bảo Lâm', '680', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (500, 'Huyện Đạ Huoai', '681', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (501, 'Huyện Đạ Tẻh', '682', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (502, 'Huyện Cát Tiên', '683', 'VN', '68', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (503, 'Thị xã Phước Long', '688', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (504, 'Thành phố Đồng Xoài', '689', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (505, 'Thị xã Bình Long', '690', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (506, 'Huyện Bù Gia Mập', '691', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (507, 'Huyện Lộc Ninh', '692', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (508, 'Huyện Bù Đốp', '693', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (509, 'Huyện Hớn Quản', '694', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (510, 'Huyện Đồng Phú', '695', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (511, 'Huyện Bù Đăng', '696', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (512, 'Huyện Chơn Thành', '697', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (513, 'Huyện Phú Riềng', '698', 'VN', '70', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (514, 'Thành phố Tây Ninh', '703', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (515, 'Huyện Tân Biên', '705', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (516, 'Huyện Tân Châu', '706', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (517, 'Huyện Dương Minh Châu', '707', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (518, 'Huyện Châu Thành', '708', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (519, 'Thị xã Hòa Thành', '709', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (520, 'Huyện Gò Dầu', '710', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (521, 'Huyện Bến Cầu', '711', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (522, 'Thị xã Trảng Bàng', '712', 'VN', '72', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (523, 'Thành phố Thủ Dầu Một', '718', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (524, 'Huyện Bàu Bàng', '719', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (525, 'Huyện Dầu Tiếng', '720', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (526, 'Thị xã Bến Cát', '721', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (527, 'Huyện Phú Giáo', '722', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (528, 'Thị xã Tân Uyên', '723', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (529, 'Thành phố Dĩ An', '724', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (530, 'Thành phố Thuận An', '725', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (531, 'Huyện Bắc Tân Uyên', '726', 'VN', '74', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (532, 'Thành phố Biên Hòa', '731', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (533, 'Thành phố Long Khánh', '732', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (534, 'Huyện Tân Phú', '734', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (535, 'Huyện Vĩnh Cửu', '735', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (536, 'Huyện Định Quán', '736', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (537, 'Huyện Trảng Bom', '737', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (538, 'Huyện Thống Nhất', '738', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (539, 'Huyện Cẩm Mỹ', '739', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (540, 'Huyện Long Thành', '740', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (541, 'Huyện Xuân Lộc', '741', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (542, 'Huyện Nhơn Trạch', '742', 'VN', '75', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (543, 'Thành phố Vũng Tàu', '747', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (544, 'Thành phố Bà Rịa', '748', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (545, 'Huyện Châu Đức', '750', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (546, 'Huyện Xuyên Mộc', '751', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (547, 'Huyện Long Điền', '752', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (548, 'Huyện Đất Đỏ', '753', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (549, 'Thị xã Phú Mỹ', '754', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (550, 'Huyện Côn Đảo', '755', 'VN', '77', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (551, 'Quận 1', '760', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (552, 'Quận 12', '761', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (553, 'Quận Gò Vấp', '764', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (554, 'Quận Bình Thạnh', '765', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (555, 'Quận Tân Bình', '766', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (556, 'Quận Tân Phú', '767', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (557, 'Quận Phú Nhuận', '768', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (558, 'Thành phố Thủ Đức', '769', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (559, 'Quận 3', '770', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (560, 'Quận 10', '771', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (561, 'Quận 11', '772', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (562, 'Quận 4', '773', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (563, 'Quận 5', '774', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (564, 'Quận 6', '775', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (565, 'Quận 8', '776', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (566, 'Quận Bình Tân', '777', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (567, 'Quận 7', '778', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (568, 'Huyện Củ Chi', '783', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (569, 'Huyện Hóc Môn', '784', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (570, 'Huyện Bình Chánh', '785', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (571, 'Huyện Nhà Bè', '786', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (572, 'Huyện Cần Giờ', '787', 'VN', '79', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (573, 'Thành phố Tân An', '794', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (574, 'Thị xã Kiến Tường', '795', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (575, 'Huyện Tân Hưng', '796', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (576, 'Huyện Vĩnh Hưng', '797', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (577, 'Huyện Mộc Hóa', '798', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (578, 'Huyện Tân Thạnh', '799', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (579, 'Huyện Thạnh Hóa', '800', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (580, 'Huyện Đức Huệ', '801', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (581, 'Huyện Đức Hòa', '802', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (582, 'Huyện Bến Lức', '803', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (583, 'Huyện Thủ Thừa', '804', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (584, 'Huyện Tân Trụ', '805', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (585, 'Huyện Cần Đước', '806', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (586, 'Huyện Cần Giuộc', '807', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (587, 'Huyện Châu Thành', '808', 'VN', '80', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (588, 'Thành phố Mỹ Tho', '815', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (589, 'Thị xã Gò Công', '816', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (590, 'Thị xã Cai Lậy', '817', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (591, 'Huyện Tân Phước', '818', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (592, 'Huyện Cái Bè', '819', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (593, 'Huyện Cai Lậy', '820', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (594, 'Huyện Châu Thành', '821', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (595, 'Huyện Chợ Gạo', '822', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (596, 'Huyện Gò Công Tây', '823', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (597, 'Huyện Gò Công Đông', '824', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (598, 'Huyện Tân Phú Đông', '825', 'VN', '82', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (599, 'Thành phố Bến Tre', '829', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (600, 'Huyện Châu Thành', '831', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (601, 'Huyện Chợ Lách', '832', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (602, 'Huyện Mỏ Cày Nam', '833', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (603, 'Huyện Giồng Trôm', '834', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (604, 'Huyện Bình Đại', '835', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (605, 'Huyện Ba Tri', '836', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (606, 'Huyện Thạnh Phú', '837', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (607, 'Huyện Mỏ Cày Bắc', '838', 'VN', '83', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (608, 'Thành phố Trà Vinh', '842', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (609, 'Huyện Càng Long', '844', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (610, 'Huyện Cầu Kè', '845', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (611, 'Huyện Tiểu Cần', '846', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (612, 'Huyện Châu Thành', '847', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (613, 'Huyện Cầu Ngang', '848', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (614, 'Huyện Trà Cú', '849', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (615, 'Huyện Duyên Hải', '850', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (616, 'Thị xã Duyên Hải', '851', 'VN', '84', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (617, 'Thành phố Vĩnh Long', '855', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (618, 'Huyện Long Hồ', '857', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (619, 'Huyện Mang Thít', '858', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (620, 'Huyện Vũng Liêm', '859', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (621, 'Huyện Tam Bình', '860', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (622, 'Thị xã Bình Minh', '861', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (623, 'Huyện Trà Ôn', '862', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (624, 'Huyện Bình Tân', '863', 'VN', '86', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (625, 'Thành phố Cao Lãnh', '866', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (626, 'Thành phố Sa Đéc', '867', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (627, 'Thành phố Hồng Ngự', '868', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (628, 'Huyện Tân Hồng', '869', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (629, 'Huyện Hồng Ngự', '870', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (630, 'Huyện Tam Nông', '871', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (631, 'Huyện Tháp Mười', '872', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (632, 'Huyện Cao Lãnh', '873', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (633, 'Huyện Thanh Bình', '874', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (634, 'Huyện Lấp Vò', '875', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (635, 'Huyện Lai Vung', '876', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (636, 'Huyện Châu Thành', '877', 'VN', '87', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (637, 'Thành phố Long Xuyên', '883', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (638, 'Thành phố Châu Đốc', '884', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (639, 'Huyện An Phú', '886', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (640, 'Thị xã Tân Châu', '887', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (641, 'Huyện Phú Tân', '888', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (642, 'Huyện Châu Phú', '889', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (643, 'Huyện Tịnh Biên', '890', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (644, 'Huyện Tri Tôn', '891', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (645, 'Huyện Châu Thành', '892', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (646, 'Huyện Chợ Mới', '893', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (647, 'Huyện Thoại Sơn', '894', 'VN', '89', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (648, 'Thành phố Rạch Giá', '899', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (649, 'Thành phố Hà Tiên', '900', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (650, 'Huyện Kiên Lương', '902', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (651, 'Huyện Hòn Đất', '903', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (652, 'Huyện Tân Hiệp', '904', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (653, 'Huyện Châu Thành', '905', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (654, 'Huyện Giồng Riềng', '906', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (655, 'Huyện Gò Quao', '907', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (656, 'Huyện An Biên', '908', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (657, 'Huyện An Minh', '909', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (658, 'Huyện Vĩnh Thuận', '910', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (659, 'Thành phố Phú Quốc', '911', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (660, 'Huyện Kiên Hải', '912', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (661, 'Huyện U Minh Thượng', '913', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (662, 'Huyện Giang Thành', '914', 'VN', '91', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (663, 'Quận Ninh Kiều', '916', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (664, 'Quận Ô Môn', '917', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (665, 'Quận Bình Thuỷ', '918', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (666, 'Quận Cái Răng', '919', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (667, 'Quận Thốt Nốt', '923', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (668, 'Huyện Vĩnh Thạnh', '924', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (669, 'Huyện Cờ Đỏ', '925', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (670, 'Huyện Phong Điền', '926', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (671, 'Huyện Thới Lai', '927', 'VN', '92', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (672, 'Thành phố Vị Thanh', '930', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (673, 'Thành phố Ngã Bảy', '931', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (674, 'Huyện Châu Thành A', '932', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (675, 'Huyện Châu Thành', '933', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (676, 'Huyện Phụng Hiệp', '934', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (677, 'Huyện Vị Thuỷ', '935', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (678, 'Huyện Long Mỹ', '936', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (679, 'Thị xã Long Mỹ', '937', 'VN', '93', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (680, 'Thành phố Sóc Trăng', '941', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (681, 'Huyện Châu Thành', '942', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (682, 'Huyện Kế Sách', '943', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (683, 'Huyện Mỹ Tú', '944', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (684, 'Huyện Cù Lao Dung', '945', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (685, 'Huyện Long Phú', '946', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (686, 'Huyện Mỹ Xuyên', '947', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (687, 'Thị xã Ngã Năm', '948', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (688, 'Huyện Thạnh Trị', '949', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (689, 'Thị xã Vĩnh Châu', '950', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (690, 'Huyện Trần Đề', '951', 'VN', '94', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (691, 'Thành phố Bạc Liêu', '954', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (692, 'Huyện Hồng Dân', '956', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (693, 'Huyện Phước Long', '957', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (694, 'Huyện Vĩnh Lợi', '958', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (695, 'Thị xã Giá Rai', '959', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (696, 'Huyện Đông Hải', '960', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (697, 'Huyện Hoà Bình', '961', 'VN', '95', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (698, 'Thành phố Cà Mau', '964', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (699, 'Huyện U Minh', '966', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (700, 'Huyện Thới Bình', '967', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (701, 'Huyện Trần Văn Thời', '968', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (702, 'Huyện Cái Nước', '969', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (703, 'Huyện Đầm Dơi', '970', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (704, 'Huyện Năm Căn', '971', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (705, 'Huyện Phú Tân', '972', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
INSERT INTO `districts` VALUES (706, 'Huyện Ngọc Hiển', '973', 'VN', '96', 'A', NULL, NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
